sudo: required
language: generic
services:
  - docker

before_install:
  - docker build  -t ismdotmsi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ismdotmsi/docker-react npm run test
