sudo: required
language: generic
services:
  - docker

before_install:
  - docker build  -t ismdotmsi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ismdotmsi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "ism-docker-react"
  env: "Ismdockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-085107194442"
  bucket_path: "ism-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
